### ISSUE TITLE
Test case problem

### ISSUE THREAD

**Issue by oguzzkck** [ahmedfgad/NumPyANN#3]

**Comment by oguzzkck** [comment]
Thank you for all your helps.

We done train.

![Attachment](https://user-images.githubusercontent.com/33704184/57455705-68b55d80-7274-11e9-8af5-0f90078b14cd.png)

So how can we test on the other images this project?

**Comment by ahmedfgad** [comment]
Good luck.
Note that this project (https://github.com/ahmedfgad/NumPyANN) uses the learning rate only for updating the ANN weights. It is not recommended. But you can still do predictions using the predict_outputs() function inside the ann_numpy.py file. Its header is as follows:
`def predict_outputs(weights, data_inputs, activation="relu")`
It accepts the latest weights in addition to the inputs to be classified and returns their class labels.

But this project uses just the learning rate for slightly modifying the weights and this does not guarantee that an acceptable accuracy will be reached.  Thus, I added an extension to this project into another project called NeuralGenetic available here: https://github.com/ahmedfgad/NeuralGenetic. It uses the genetic algorithm for training the ANN better than before. The NeuralGenetic project is not away from the NumPyANN project as it still uses the previously extracted features in NumPyANN and also builds the ANN using the same code used in NumPyANN. It just changes the way in which the weights are updated.
After training the ANN completes, you can make predictions using the predict_outputs() function.

Good luck.
