### ISSUE TITLE
Reducing Feature Vector

### ISSUE THREAD

**Issue by murat199** [ahmedfgad/NumPyANN#4]
I didn't understand how and why you reducing feature vector than 360 to 102.

**Comment by ahmedfgad** [comment]
There are a number of reasons for reducing the feature vector. One reason may be the existence of some bad elements (i.e. irrelevant) within the feature vector that might hurt the accuracy later. Another reason might be that the feature vector is very long and thus it will be time-consuming to training a model accordingly. In this project, the length of 360 is not a big value and using the original feature vector might not slow down the training process.
The main reason for doing feature reduction is that this project is part of my book **Ahmed Fawzy Gad 'Practical Computer Vision Applications Using Deep Learning with CNNs'. Dec. 2018, Apress, 978-1-4842-4167-7**. The project aims to cover the machine learning pipeline in one of its chapters to make it obvious that some feature vectors might be reduced without a noticeable reduction in the accuracy. This is the main reason.
