### ISSUE TITLE
PyGad is not a package and other modules can not be imported

### ISSUE THREAD

**Issue by mhelal** [ahmedfgad/NumPyANN#7]
Hello

I can not run the NumpyANN examples because of this error:

ModuleNotFoundError: No module named 'pygad.nn'; 'pygad' is not a package

and I can not install using pip pygad.nn or other examples in 

I solved the problem now by import nn because it is in the same folder

and all examples instead of pygad.nn, just nn

I hope you fix such that the examples can run without corrections, or let me know what I have done wrong to receive this error, 

thank you, 

Manal

**Comment by ahmedfgad** [comment]
Hello,

You should install `pygad` not `pygad.nn`. Please use this command:
`pip3 install pygad`

After PyGAD is installed, you should use `pygad.nn` not just `nn`. This way you can run the code examples posted at GitHub or the [documentation](https://pygad.readthedocs.io) without making any change.

Please have a try and let me know.
