### ISSUE TITLE
Import error (numpy int)

### ISSUE THREAD

**Issue by erdmsen** [ahmedfgad/NumPyANN#9]
hello, 
i experience this error lately:

![zeqa6lbv05j51 (1)](https://user-images.githubusercontent.com/56255271/215287669-20ee9d30-14c9-4564-973c-879ebd71f41a.png)

it doesn't work

**Comment by ahmedfgad** [comment]
Hi @erdmsen,

A new release will be pushed soon that fixes the issue. For now, you can downgrade `numpy`.
